build: false

environment:
    PYTHON_VERSION: "2.7"
    PYTHON_ARCH: "64"
    MINICONDA: C:\Miniconda-x64

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% pandas nose"
  - activate test-environment

test_script:
  - python setup.py install
  - nosetests -v
